"use client";

import { CheckCircle2, KeyRound } from "lucide-react";
import Link from "next/link";
import { memo, useCallback, useState, type FormEvent } from "react";

import { Input, Panel } from "@/app/_components/shared-ui";
import { browserApi } from "@/lib/browser-api";
import { ResidentHeader, Message, field } from "./resident-shared";

export const ResidentActivationPageContent = memo(function ResidentActivationPageContent() {
  const [message, setMessage] = useState("");
  const [activated, setActivated] = useState(false);

  const handleActivate = useCallback(async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const form = new FormData(event.currentTarget);

    try {
      await browserApi("/api/v1/resident/activate", {
        body: JSON.stringify({
          code: field(form, "code"),
          deviceInfo: { source: "web" },
          sessionInfo: { activatedAt: new Date().toISOString() },
        }),
        method: "POST",
      });
      setActivated(true);
      setMessage("Resident access activated.");
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "Activation failed.");
    }
  }, []);

  return (
    <div className="min-h-screen bg-background px-4 py-10 text-foreground">
      <div className="mx-auto max-w-lg space-y-5">
        <ResidentHeader
          description="Enter the code generated by your hostel admin."
          icon={KeyRound}
          title="Resident Activation"
        />
        <Message value={message} />
        <Panel>
          {activated ? (
            <div className="space-y-4 text-center">
              <CheckCircle2 className="mx-auto size-12 text-role-resident" />
              <p className="text-lg font-semibold text-primary">Activation complete</p>
              <Link
                className="inline-flex h-11 items-center justify-center rounded-md bg-role-resident px-4 text-sm font-semibold text-white"
                href="/resident/dashboard"
              >
                Open Dashboard
              </Link>
            </div>
          ) : (
            <form className="grid gap-4" onSubmit={handleActivate}>
              <Input label="Activation code" name="code" required />
              <button className="h-11 rounded-md bg-role-resident text-sm font-semibold text-white">
                Activate
              </button>
            </form>
          )}
        </Panel>
      </div>
    </div>
  );
});
