"use client";

import {
  Bell,
  CheckCircle2,
  CreditCard,
  Home,
  KeyRound,
  ReceiptText,
  Send,
  Upload,
  UserRound,
  Utensils,
} from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";

import {
  EmptyState,
  Input,
  LoadingRows,
  Panel,
  Select,
  StatusBadge,
  TextArea,
  currency,
} from "@/app/_components/hostel-admin-operations-pages";
import { browserApi } from "@/lib/browser-api";

type LoadState = "idle" | "loading" | "ready" | "error";

type ResidentSummary = {
  depositAmount: number;
  email?: string;
  firstName: string;
  fullName?: string;
  id: string;
  lastName: string;
  phone: string;
  status: string;
};

type ResidentDashboard = {
  complaints: {
    openCount: number;
  };
  feeStatus: {
    dueAmount: number;
    latestPayment?: Payment | null;
    pendingProofs: number;
    unpaidCount: number;
  };
  foodMenu: FoodMenu[];
  hostel: {
    contact?: {
      email?: string;
      phone?: string;
    };
    location?: {
      area?: string;
      city?: string;
    };
    name: string;
    photoUrl?: string;
  } | null;
  nightStatus: {
    checkedAt: string | null;
    status: string;
  };
  notices: Notice[];
  resident: ResidentSummary;
  roomBed: {
    bed: {
      bedNumber: string;
      status: string;
    } | null;
    room: {
      roomNumber: string;
      roomType: string;
    } | null;
  };
};

type Payment = {
  dueAmount: number;
  dueDate: string;
  id: string;
  month: string;
  paidAmount: number;
  status: "UNPAID" | "PAID" | "PARTIAL" | "OVERDUE" | "PENDING_PROOF";
};

type PaymentProof = {
  id: string;
  paymentId: string;
  proofImageAssetId: string;
  status: "PENDING" | "APPROVED" | "REJECTED";
  transactionCode?: string;
};

type FoodMenu = {
  date: string;
  id: string;
  items: string[];
  mealType: "BREAKFAST" | "LUNCH" | "SNACKS" | "DINNER";
  timing: string;
};

type FoodPhoto = {
  caption?: string;
  date: string;
  id: string;
  mealType: string;
  photoAssetId: string;
};

type Notice = {
  category: string;
  content: string;
  id: string;
  isRead?: boolean;
  isUrgent: boolean;
  publishedAt?: string;
  readAt?: string;
  title: string;
};

function field(form: FormData, name: string) {
  const value = form.get(name);

  return typeof value === "string" ? value.trim() : "";
}

function optionalField(form: FormData, name: string) {
  const value = field(form, name);

  return value.length > 0 ? value : undefined;
}

function ResidentHeader({
  description,
  icon: Icon,
  title,
}: {
  description: string;
  icon: typeof Home;
  title: string;
}) {
  return (
    <div className="flex items-start gap-3">
      <span className="rounded-lg bg-role-resident-soft p-3 text-role-resident">
        <Icon className="size-5" />
      </span>
      <div>
        <h1 className="font-heading text-3xl font-bold text-primary">{title}</h1>
        <p className="mt-1 max-w-3xl text-sm text-muted-foreground">{description}</p>
      </div>
    </div>
  );
}

function Message({ value }: { value: string }) {
  return value ? (
    <div className="rounded-lg border border-border bg-muted/40 p-3 text-sm">{value}</div>
  ) : null;
}

export function ResidentActivationPageContent() {
  const [message, setMessage] = useState("");
  const [activated, setActivated] = useState(false);

  async function handleActivate(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);

    try {
      await browserApi("/api/v1/resident/activate", {
        body: JSON.stringify({
          code: field(form, "code"),
          deviceInfo: { source: "web" },
          sessionInfo: { activatedAt: new Date().toISOString() },
        }),
        method: "POST",
      });
      setActivated(true);
      setMessage("Resident access activated.");
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "Activation failed.");
    }
  }

  return (
    <div className="min-h-screen bg-background px-4 py-10 text-foreground">
      <div className="mx-auto max-w-lg space-y-5">
        <ResidentHeader
          description="Enter the code generated by your hostel admin."
          icon={KeyRound}
          title="Resident Activation"
        />
        <Message value={message} />
        <Panel>
          {activated ? (
            <div className="space-y-4 text-center">
              <CheckCircle2 className="mx-auto size-12 text-role-resident" />
              <p className="text-lg font-semibold text-primary">Activation complete</p>
              <Link
                className="inline-flex h-11 items-center justify-center rounded-md bg-role-resident px-4 text-sm font-semibold text-white"
                href="/resident/dashboard"
              >
                Open Dashboard
              </Link>
            </div>
          ) : (
            <form className="grid gap-4" onSubmit={handleActivate}>
              <Input label="Activation code" name="code" required />
              <button className="h-11 rounded-md bg-role-resident text-sm font-semibold text-white">
                Activate
              </button>
            </form>
          )}
        </Panel>
      </div>
    </div>
  );
}

export function ResidentDashboardPageContent() {
  const [dashboard, setDashboard] = useState<ResidentDashboard | null>(null);
  const [state, setState] = useState<LoadState>("idle");
  const [message, setMessage] = useState("");

  const load = useCallback(async () => {
    setState("loading");
    try {
      const data = await browserApi<{ dashboard: ResidentDashboard }>(
        "/api/v1/resident/dashboard",
      );

      setDashboard(data.dashboard);
      setState("ready");
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "Could not load dashboard.");
      setState("error");
    }
  }, []);

  useEffect(() => {
    const timer = window.setTimeout(() => {
      void load();
    }, 0);

    return () => window.clearTimeout(timer);
  }, [load]);

  return (
    <div className="mx-auto max-w-[1448px] space-y-6">
      <ResidentHeader
        description="Your room, dues, notices, menu, and daily status."
        icon={Home}
        title="Resident Dashboard"
      />
      <Message value={message} />
      {state === "loading" ? <LoadingRows /> : null}
      {state === "error" ? <EmptyState label="Dashboard could not be loaded." /> : null}
      {dashboard ? (
        <>
          <div className="grid gap-4 md:grid-cols-4">
            {[
              [
                "Room / Bed",
                `${dashboard.roomBed.room?.roomNumber ?? "-"} / ${dashboard.roomBed.bed?.bedNumber ?? "-"}`,
              ],
              ["Due Amount", currency(dashboard.feeStatus.dueAmount)],
              [
                "Unread Notices",
                String(dashboard.notices.filter((notice) => !notice.isRead).length),
              ],
              ["Night Status", dashboard.nightStatus.status],
            ].map(([label, value]) => (
              <Panel key={label}>
                <p className="text-sm text-muted-foreground">{label}</p>
                <p className="mt-2 text-2xl font-bold text-primary">{value}</p>
              </Panel>
            ))}
          </div>
          <div className="grid gap-5 xl:grid-cols-[1fr_1fr_360px]">
            <Panel title="Hostel">
              <p className="text-xl font-bold text-primary">
                {dashboard.hostel?.name ?? "Hostel"}
              </p>
              <p className="mt-2 text-sm text-muted-foreground">
                {dashboard.hostel?.location?.area} {dashboard.hostel?.location?.city}
              </p>
              <p className="mt-4 text-sm text-muted-foreground">
                {dashboard.hostel?.contact?.phone} {dashboard.hostel?.contact?.email}
              </p>
            </Panel>
            <Panel title="Today's Menu">
              {dashboard.foodMenu.length === 0 ? (
                <EmptyState label="No menu posted." />
              ) : null}
              <div className="space-y-3">
                {dashboard.foodMenu.map((menu) => (
                  <div className="rounded-lg border border-border p-3" key={menu.id}>
                    <div className="flex items-center justify-between gap-3">
                      <p className="font-semibold text-primary">{menu.mealType}</p>
                      <span className="text-xs text-muted-foreground">{menu.timing}</span>
                    </div>
                    <p className="mt-2 text-sm text-muted-foreground">
                      {menu.items.join(", ")}
                    </p>
                  </div>
                ))}
              </div>
            </Panel>
            <Panel title="Quick Actions">
              <div className="grid gap-2">
                {[
                  ["/resident/payments", "Payments", CreditCard],
                  ["/resident/food", "Food", Utensils],
                  ["/resident/notices", "Notices", Bell],
                  ["/resident/profile", "Profile", UserRound],
                ].map(([href, label, Icon]) => {
                  const ActionIcon = Icon as typeof Home;

                  return (
                    <Link
                      className="inline-flex items-center gap-3 rounded-md border border-border px-3 py-2 text-sm font-semibold text-primary hover:bg-muted"
                      href={href as string}
                      key={href as string}
                    >
                      <ActionIcon className="size-4 text-role-resident" />
                      {label as string}
                    </Link>
                  );
                })}
              </div>
            </Panel>
          </div>
          <Panel title="Recent Notices">
            {dashboard.notices.length === 0 ? <EmptyState label="No notices." /> : null}
            <div className="space-y-3">
              {dashboard.notices.map((notice) => (
                <div className="rounded-lg border border-border p-4" key={notice.id}>
                  <div className="flex items-start justify-between gap-3">
                    <p className="font-semibold text-primary">{notice.title}</p>
                    {notice.isUrgent ? <StatusBadge>URGENT</StatusBadge> : null}
                  </div>
                  <p className="mt-1 text-sm text-muted-foreground">{notice.content}</p>
                </div>
              ))}
            </div>
          </Panel>
        </>
      ) : null}
    </div>
  );
}

export function ResidentPaymentsPageContent() {
  const [payments, setPayments] = useState<Payment[]>([]);
  const [proofs, setProofs] = useState<PaymentProof[]>([]);
  const [state, setState] = useState<LoadState>("idle");
  const [message, setMessage] = useState("");

  const proofByPaymentId = useMemo(
    () => new Map(proofs.map((proof) => [proof.paymentId, proof])),
    [proofs],
  );

  const load = useCallback(async () => {
    setState("loading");
    try {
      const data = await browserApi<{ payments: Payment[]; proofs: PaymentProof[] }>(
        "/api/v1/resident/payments",
      );

      setPayments(data.payments);
      setProofs(data.proofs);
      setState("ready");
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "Could not load payments.");
      setState("error");
    }
  }, []);

  useEffect(() => {
    const timer = window.setTimeout(() => {
      void load();
    }, 0);

    return () => window.clearTimeout(timer);
  }, [load]);

  async function handleProof(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const paymentId = field(form, "paymentId");

    try {
      await browserApi(`/api/v1/resident/payments/${paymentId}/proof`, {
        body: JSON.stringify({
          proofImageAssetId: field(form, "proofImageAssetId"),
          transactionCode: optionalField(form, "transactionCode"),
        }),
        method: "POST",
      });
      event.currentTarget.reset();
      setMessage("Proof submitted.");
      await load();
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "Could not submit proof.");
    }
  }

  return (
    <div className="mx-auto max-w-[1448px] space-y-6">
      <ResidentHeader
        description="Review monthly dues and submit payment proof."
        icon={ReceiptText}
        title="Payments"
      />
      <Message value={message} />
      <div className="grid gap-5 xl:grid-cols-[1fr_360px]">
        <Panel title="Payment Records">
          {state === "loading" ? <LoadingRows /> : null}
          {state === "error" ? (
            <EmptyState label="Payments could not be loaded." />
          ) : null}
          {state === "ready" && payments.length === 0 ? (
            <EmptyState label="No payments." />
          ) : null}
          <div className="space-y-3">
            {payments.map((payment) => {
              const proof = proofByPaymentId.get(payment.id);

              return (
                <div className="rounded-lg border border-border p-4" key={payment.id}>
                  <div className="flex flex-wrap items-start justify-between gap-3">
                    <div>
                      <p className="font-semibold text-primary">{payment.month}</p>
                      <p className="mt-1 text-sm text-muted-foreground">
                        Due {new Date(payment.dueDate).toLocaleDateString()}
                      </p>
                    </div>
                    <StatusBadge>{payment.status}</StatusBadge>
                  </div>
                  <div className="mt-4 grid gap-3 text-sm md:grid-cols-3">
                    <span>Due: {currency(payment.dueAmount)}</span>
                    <span>Paid: {currency(payment.paidAmount)}</span>
                    <span>Proof: {proof?.status ?? "Not submitted"}</span>
                  </div>
                </div>
              );
            })}
          </div>
        </Panel>
        <Panel title="Submit Proof">
          <form className="grid gap-3" onSubmit={handleProof}>
            <Select label="Payment" name="paymentId" required>
              <option value="">Select payment</option>
              {payments
                .filter((payment) => payment.status !== "PAID")
                .map((payment) => (
                  <option key={payment.id} value={payment.id}>
                    {payment.month} / {currency(payment.dueAmount)}
                  </option>
                ))}
            </Select>
            <Input label="Proof image asset id" name="proofImageAssetId" required />
            <Input label="Transaction code" name="transactionCode" />
            <button className="inline-flex h-11 items-center justify-center gap-2 rounded-md bg-role-resident text-sm font-semibold text-white">
              <Upload className="size-4" />
              Submit Proof
            </button>
          </form>
        </Panel>
      </div>
    </div>
  );
}

export function ResidentFoodPageContent() {
  const [menus, setMenus] = useState<FoodMenu[]>([]);
  const [photos, setPhotos] = useState<FoodPhoto[]>([]);
  const [state, setState] = useState<LoadState>("idle");
  const [message, setMessage] = useState("");

  const load = useCallback(async () => {
    setState("loading");
    try {
      const data = await browserApi<{ menus: FoodMenu[]; photos: FoodPhoto[] }>(
        "/api/v1/resident/food",
      );

      setMenus(data.menus);
      setPhotos(data.photos);
      setState("ready");
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "Could not load food.");
      setState("error");
    }
  }, []);

  useEffect(() => {
    const timer = window.setTimeout(() => {
      void load();
    }, 0);

    return () => window.clearTimeout(timer);
  }, [load]);

  async function handleFeedback(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);

    try {
      await browserApi("/api/v1/resident/food/feedback", {
        body: JSON.stringify({
          comment: optionalField(form, "comment"),
          date: field(form, "date"),
          isAnonymous: form.get("isAnonymous") === "on",
          mealType: field(form, "mealType"),
          menuId: optionalField(form, "menuId"),
          rating: Number(field(form, "rating")),
        }),
        method: "POST",
      });
      event.currentTarget.reset();
      setMessage("Feedback submitted.");
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "Could not submit feedback.");
    }
  }

  async function handlePhoto(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);

    try {
      await browserApi("/api/v1/resident/food/photos", {
        body: JSON.stringify({
          caption: optionalField(form, "caption"),
          date: field(form, "date"),
          mealType: field(form, "mealType"),
          photoAssetId: field(form, "photoAssetId"),
        }),
        method: "POST",
      });
      event.currentTarget.reset();
      setMessage("Food photo uploaded.");
      await load();
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "Could not upload photo.");
    }
  }

  return (
    <div className="mx-auto max-w-[1448px] space-y-6">
      <ResidentHeader
        description="View menu updates, food photos, and send feedback."
        icon={Utensils}
        title="Food"
      />
      <Message value={message} />
      <div className="grid gap-5 xl:grid-cols-[1fr_380px]">
        <Panel title="Menu">
          {state === "loading" ? <LoadingRows /> : null}
          {state === "error" ? <EmptyState label="Food could not be loaded." /> : null}
          {state === "ready" && menus.length === 0 ? (
            <EmptyState label="No menu posted." />
          ) : null}
          <div className="grid gap-3 md:grid-cols-2">
            {menus.map((menu) => (
              <div className="rounded-lg border border-border p-4" key={menu.id}>
                <div className="flex items-start justify-between gap-3">
                  <p className="font-semibold text-primary">{menu.mealType}</p>
                  <span className="text-xs text-muted-foreground">{menu.timing}</span>
                </div>
                <p className="mt-2 text-sm text-muted-foreground">
                  {menu.items.join(", ")}
                </p>
              </div>
            ))}
          </div>
          <div className="mt-5 grid gap-3 md:grid-cols-3">
            {photos.map((photo) => (
              <div className="rounded-lg border border-border p-3" key={photo.id}>
                <p className="font-semibold text-primary">{photo.mealType}</p>
                <p className="mt-1 text-xs text-muted-foreground">{photo.photoAssetId}</p>
                <p className="mt-2 text-sm text-muted-foreground">{photo.caption}</p>
              </div>
            ))}
          </div>
        </Panel>
        <div className="space-y-5">
          <Panel title="Send Feedback">
            <form className="grid gap-3" onSubmit={handleFeedback}>
              <Select label="Menu" name="menuId">
                <option value="">General feedback</option>
                {menus.map((menu) => (
                  <option key={menu.id} value={menu.id}>
                    {menu.mealType} / {new Date(menu.date).toLocaleDateString()}
                  </option>
                ))}
              </Select>
              <Input label="Date" name="date" required type="date" />
              <Select label="Meal" name="mealType" required>
                {["BREAKFAST", "LUNCH", "SNACKS", "DINNER"].map((meal) => (
                  <option key={meal} value={meal}>
                    {meal}
                  </option>
                ))}
              </Select>
              <Input label="Rating" name="rating" required type="number" />
              <TextArea label="Comment" name="comment" />
              <label className="flex items-center gap-2 text-sm text-primary">
                <input name="isAnonymous" type="checkbox" />
                Anonymous
              </label>
              <button className="inline-flex h-11 items-center justify-center gap-2 rounded-md bg-role-resident text-sm font-semibold text-white">
                <Send className="size-4" />
                Submit
              </button>
            </form>
          </Panel>
          <Panel title="Upload Photo">
            <form className="grid gap-3" onSubmit={handlePhoto}>
              <Input label="Photo asset id" name="photoAssetId" required />
              <Input label="Date" name="date" required type="date" />
              <Select label="Meal" name="mealType" required>
                {["BREAKFAST", "LUNCH", "SNACKS", "DINNER"].map((meal) => (
                  <option key={meal} value={meal}>
                    {meal}
                  </option>
                ))}
              </Select>
              <Input label="Caption" name="caption" />
              <button className="h-11 rounded-md border border-role-resident text-sm font-semibold text-role-resident">
                Upload Photo
              </button>
            </form>
          </Panel>
        </div>
      </div>
    </div>
  );
}

export function ResidentNoticesPageContent() {
  const [notices, setNotices] = useState<Notice[]>([]);
  const [state, setState] = useState<LoadState>("idle");
  const [message, setMessage] = useState("");

  const load = useCallback(async () => {
    setState("loading");
    try {
      const data = await browserApi<{ notices: Notice[] }>("/api/v1/resident/notices");

      setNotices(data.notices);
      setState("ready");
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "Could not load notices.");
      setState("error");
    }
  }, []);

  useEffect(() => {
    const timer = window.setTimeout(() => {
      void load();
    }, 0);

    return () => window.clearTimeout(timer);
  }, [load]);

  async function markRead(noticeId: string) {
    try {
      await browserApi(`/api/v1/resident/notices/${noticeId}/read`, {
        body: JSON.stringify({}),
        method: "PATCH",
      });
      await load();
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "Could not mark notice read.");
    }
  }

  return (
    <div className="mx-auto max-w-[1448px] space-y-6">
      <ResidentHeader
        description="Read hostel notices and keep your feed up to date."
        icon={Bell}
        title="Notices"
      />
      <Message value={message} />
      <Panel>
        {state === "loading" ? <LoadingRows /> : null}
        {state === "error" ? <EmptyState label="Notices could not be loaded." /> : null}
        {state === "ready" && notices.length === 0 ? (
          <EmptyState label="No notices." />
        ) : null}
        <div className="space-y-3">
          {notices.map((notice) => (
            <div className="rounded-lg border border-border p-4" key={notice.id}>
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div>
                  <div className="flex flex-wrap items-center gap-2">
                    <p className="font-semibold text-primary">{notice.title}</p>
                    {notice.isUrgent ? <StatusBadge>URGENT</StatusBadge> : null}
                    <StatusBadge>{notice.category}</StatusBadge>
                  </div>
                  <p className="mt-2 text-sm text-muted-foreground">{notice.content}</p>
                </div>
                {notice.isRead ? (
                  <StatusBadge>READ</StatusBadge>
                ) : (
                  <button
                    className="rounded-md bg-role-resident px-3 py-2 text-sm font-semibold text-white"
                    onClick={() => void markRead(notice.id)}
                    type="button"
                  >
                    Mark Read
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      </Panel>
    </div>
  );
}

export function ResidentProfilePageContent() {
  const [profile, setProfile] = useState<{
    emergencyContacts: Array<{
      id: string;
      name: string;
      phone: string;
      relation: string;
    }>;
    guardians: Array<{
      firstName: string;
      id: string;
      lastName: string;
      phone: string;
      relation: string;
    }>;
    resident: ResidentSummary;
    roomBed: ResidentDashboard["roomBed"];
  } | null>(null);
  const [state, setState] = useState<LoadState>("idle");
  const [message, setMessage] = useState("");

  useEffect(() => {
    async function load() {
      setState("loading");
      try {
        const data = await browserApi<{ profile: NonNullable<typeof profile> }>(
          "/api/v1/resident/profile",
        );

        setProfile(data.profile);
        setState("ready");
      } catch (error) {
        setMessage(error instanceof Error ? error.message : "Could not load profile.");
        setState("error");
      }
    }

    void load();
  }, []);

  return (
    <div className="mx-auto max-w-[1448px] space-y-6">
      <ResidentHeader
        description="Your resident record and hostel contact information."
        icon={UserRound}
        title="My Profile"
      />
      <Message value={message} />
      {state === "loading" ? <LoadingRows /> : null}
      {state === "error" ? <EmptyState label="Profile could not be loaded." /> : null}
      {profile ? (
        <div className="grid gap-5 xl:grid-cols-3">
          <Panel title="Resident">
            <p className="text-xl font-bold text-primary">
              {profile.resident.firstName} {profile.resident.lastName}
            </p>
            <p className="mt-2 text-sm text-muted-foreground">{profile.resident.phone}</p>
            <p className="mt-1 text-sm text-muted-foreground">{profile.resident.email}</p>
            <div className="mt-4">
              <StatusBadge>{profile.resident.status}</StatusBadge>
            </div>
          </Panel>
          <Panel title="Room & Bed">
            <p className="text-sm text-muted-foreground">Room</p>
            <p className="mt-1 text-2xl font-bold text-primary">
              {profile.roomBed.room?.roomNumber ?? "-"}
            </p>
            <p className="mt-4 text-sm text-muted-foreground">Bed</p>
            <p className="mt-1 text-2xl font-bold text-primary">
              {profile.roomBed.bed?.bedNumber ?? "-"}
            </p>
          </Panel>
          <Panel title="Contacts">
            <div className="space-y-4">
              {profile.guardians.map((guardian) => (
                <div key={guardian.id}>
                  <p className="font-semibold text-primary">
                    {guardian.firstName} {guardian.lastName}
                  </p>
                  <p className="text-sm text-muted-foreground">
                    {guardian.relation} / {guardian.phone}
                  </p>
                </div>
              ))}
              {profile.emergencyContacts.map((contact) => (
                <div key={contact.id}>
                  <p className="font-semibold text-primary">{contact.name}</p>
                  <p className="text-sm text-muted-foreground">
                    {contact.relation} / {contact.phone}
                  </p>
                </div>
              ))}
            </div>
          </Panel>
        </div>
      ) : null}
    </div>
  );
}
